services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=backend'
      - 'POSTGRES_PASSWORD=backend'
      - 'POSTGRES_USER=backend'
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
